[SystemSettings]

## Scalability::GlobalIlluminationQuality ##

r.Lumen.DiffuseIndirect.Allow                               = 1
r.Lumen.HardwareRayTracing.HitLighting.Allowed              = 0

# Radiosity #

; Radiosity reduces FPS by ~3%, and it doesn't make much of a difference.

r.LumenScene.Radiosity                                      = 0

# Screen Probe Gather #

; Irradiance Field Gather is glitchy.

r.Lumen.FinalGatherMethod                                   = 1

; DownsampleFactor 1, 2, 4 are unplayable. 16+ are too noisy. 8 reduces FPS by ~25% (vs 16). 

r.Lumen.ScreenProbeGather.DownsampleFactor                  = 8

; May lower TracingOctahedronResolution for performance, but it makes shading slightly uglier.

r.Lumen.ScreenProbeGather.TracingOctahedronResolution       = 8

; https://gpuopen.com/learn/unreal-engine-performance-guide/
; StochasticInterpolation = 1 is too noisy.

r.Lumen.ScreenProbeGather.StochasticInterpolation           = 0
r.Lumen.ScreenProbeGather.SpatialFilterNumPasses            = 1
r.Lumen.ScreenProbeGather.IntegrationTileClassification     = 0

; Other

r.Lumen.ScreenProbeGather.FullResolutionJitterWidth         = 0.5

# Screen Space #

r.Lumen.ScreenProbeGather.ScreenTraces                      = 0

# DFAO #

; DFAO is required for single layer water.

r.DistanceFieldAO                   = 1
r.AOQuality                         = 2

## Scalability::ReflectionQuality ##

; https://gpuopen.com/learn/unreal-engine-performance-guide/

r.Lumen.Reflections.RadianceCache   = 1

# Screen Space #

r.SSR.Quality                                               = 0
r.Lumen.Reflections.ScreenTraces                            = 0
r.Lumen.Reflections.DistantScreenTraces                     = 0

## Scalability::ShadowQuality ##

; Unfiltered; unsure if this matters with VSM.

r.ShadowQuality                     = 1

# MegaLigths #

; MegaLights is too noisy with directional ligths right now.

r.MegaLights.DirectionalLights      = 0

; Don't downsample to avoid noise.

r.MegaLights.DownsampleMode         = 0

# Screen Space #

r.MegaLights.ScreenTraces           = 0
r.MegaLights.DistantScreenTraces    = 0

## Scalability::TextureQuality ##

r.Streaming.LimitPoolSizeToVRAM     = 1
r.Streaming.PoolSize                = 2000

## Scalability::EffectsQuality ##

r.DetailMode                        = 3
r.MaterialQualityLevel              = 3

# Screen Space #

r.SSS.Scale                         = 0

## Scalability::ViewDistanceQuality ##

r.ViewDistanceScale                 = 1.0

## Scalability::PostProcessQuality ##

r.AmbientOcclusionLevels            = 0
r.BloomQuality                      = 4
r.DepthOfFieldQuality               = 0
r.EyeAdaptationQuality              = 0
r.LensFlareQuality                  = 0
r.MotionBlurQuality                 = 0
r.SceneColorFringeQuality           = 0
r.Tonemapper.Quality                = 5

; Nearest Filtering

r.Upscale.Quality                   = 0

## Other ##

; Only cull objects behind camera.

r.RayTracing.Culling                = 1

[/Script/Engine.UserInterfaceSettings]

; TODO: RenderFocusRule = Never

RenderFocusRule                    = Always
UIScaleRule                        = Custom
CustomScalingRuleClass             = /Script/Re.ReDPIScalingRule

[/Script/Engine.Engine]

AssetManagerClassName              = /Script/Re.ReAssetManager

bSmoothFrameRate                   = false
bPauseOnLossOfFocus                = false

[/Script/UnrealEd.EditorEngine]

bSmoothFrameRate                   = false

[/Script/Engine.RendererSettings]

## Lumen ##

r.DynamicGlobalIlluminationMethod  = 1
r.ReflectionMethod                 = 1

## HWRT ##

r.RayTracing                       = True
r.Lumen.HardwareRayTracing         = True
r.PathTracing                      = False
r.RayTracing.Shadows               = True

; Surface Cache

r.Lumen.HardwareRayTracing.LightingMode                                             = 0

; HWRT Dependencies

r.SkinCache.CompileShaders                                                          = 1
r.RayTracing.RayTracingProxies.ProjectEnabled                                       = True

; Other

r.Lumen.TranslucencyReflections.FrontLayer.EnableForProject                         = True
r.Lumen.Reflections.HardwareRayTracing.Translucent.Refraction.EnableForProject      = True

## Post Processing ##

r.AntiAliasingMethod               = 0
r.DefaultFeature.AmbientOcclusion  = False
r.DefaultFeature.AutoExposure      = False
r.DefaultFeature.Bloom             = True
r.DefaultFeature.MotionBlur        = False
r.DefaultFeature.LensFlare         = False

## Other ##

r.AllowOcclusionQueries            = True
r.AllowStaticLighting              = False
r.Shadow.Virtual.Enable            = 1
r.MegaLights.EnableForProject      = True
r.GenerateMeshDistanceFields       = True
r.VirtualTextures                  = 1
r.Substrate                        = True

[/Script/EngineSettings.GameMapsSettings]

GameInstanceClass                  = /Script/Re.ReGameInstance
EditorStartupMap                   = /Game/Root/Levels/LV_Persistent.LV_Persistent
GameDefaultMap                     = /Game/Root/Levels/LV_Persistent.LV_Persistent
GlobalDefaultGameMode              = /Script/Re.ReGameMode

[/Script/Engine.CollisionProfile]

+DefaultChannelResponses           = (Channel = ECC_GameTraceChannel1, DefaultResponse = ECR_Ignore, bTraceType = True, bStaticObject = False, Name = "MovementPlane"  )
+DefaultChannelResponses           = (Channel = ECC_GameTraceChannel2, DefaultResponse = ECR_Ignore, bTraceType = True, bStaticObject = False, Name = "Interactable"   )

[/Script/HardwareTargeting.HardwareTargetingSettings]

TargetedHardwareClass              = Desktop
AppliedTargetedHardwareClass       = Desktop
DefaultGraphicsPerformance         = Scalable
AppliedDefaultGraphicsPerformance  = Scalable

[/Script/WindowsTargetPlatform.WindowsTargetSettings]

DefaultGraphicsRHI                 = DefaultGraphicsRHI_DX12
-D3D12TargetedShaderFormats        = PCD3D_SM5
+D3D12TargetedShaderFormats        = PCD3D_SM6
bGenerateNaniteFallbackMeshes      = False
