[/Script/Engine.InputSettings]

DefaultPlayerInputClass         = /Script/EnhancedInput.EnhancedPlayerInput
DefaultInputComponentClass      = /Script/EnhancedInput.EnhancedInputComponent

## Fullscreen Shortcuts ##

bAltEnterTogglesFullscreen      = True
bF11TogglesFullscreen           = True

## Mouse ##

bCaptureMouseOnLaunch           = False
bEnableMouseSmoothing           = False
bEnableFOVScaling               = False
