; https://dev.epicgames.com/documentation/unreal-engine/unreal-engine-console-variables-reference

[GlobalIlluminationQuality@3]

; DFAO is required for single layer water material. AOQuality == DFAO quality; 1 vs 2 has no performance impact.

r.DistanceFieldAO                                           = 1
r.AOQuality                                                 = 2

; FinalGatherMethod == 0 is Lumen Lite, which is a noisy/glitchy mess.
; Higher DownsampleFactor increases noise. Low values (1, 2, 4) are unplayable. Use 8/16. 8 reduces FPS by 25-30% (vs 16). 32 is too noisy.
; TracingOctahedronResolution == 4 causes terrible shadows.

r.Lumen.DiffuseIndirect.Allow                               = 1
r.Lumen.FinalGatherMethod                                   = 1
r.LumenScene.Radiosity.UpdateFactor                         = 128
r.LumenScene.Radiosity.HemisphereProbeResolution            = 8
r.Lumen.ScreenProbeGather.DownsampleFactor                  = 8
r.Lumen.ScreenProbeGather.TracingOctahedronResolution       = 8
r.Lumen.HardwareRayTracing.HitLighting.Allowed              = 0
r.Lumen.ScreenProbeGather.StochasticInterpolation           = 0

[ReflectionQuality@3]

r.SSR.Quality                                               = 0

[ShadowQuality@3]

r.DistanceFieldShadowing                                    = 0

[TextureQuality@3]

r.Streaming.LimitPoolSizeToVRAM                             = 1
r.Streaming.PoolSize                                        = 2000

[EffectsQuality@3]

r.SSS.Scale                                                 = 0
r.SSGI.Quality                                              = 0
r.MaterialQualityLevel                                      = 1
r.DetailMode                                                = 3

[PostProcessQuality@0]

r.Upscale.Quality                                           = 0
