[/Script/Engine.GameUserSettings]

; TODO: Set FrameRateLimit to 120.0 before shipping.

FrameRateLimit                      = 720.0
bUseVSync                           = False
bUseDynamicResolution               = False
FullscreenMode                      = 1
PreferredFullscreenMode             = 1
bUseHDRDisplayOutput                = False
AudioQualityLevel                   = 3
bEnableScalabilitySettings          = True

[ScalabilityGroups]

sg.ResolutionQuality                = 50
sg.GlobalIlluminationQuality        = 3
sg.ReflectionQuality                = 3
sg.ShadowQuality                    = 3
sg.ShadingQuality                   = 3
sg.ViewDistanceQuality              = 0
sg.TextureQuality                   = 3
sg.FoliageQuality                   = 3
sg.EffectsQuality                   = 3
sg.LandscapeQuality                 = 3
sg.AntiAliasingQuality              = 0
sg.PostProcessQuality               = 0
