[ConsoleVariables]



[SystemSettings]

; https://dev.epicgames.com/documentation/unreal-engine/ray-tracing-performance-guide-in-unreal-engine

r.RayTracing.Culling                = 1
r.RayTracing.Culling.Radius         = 20000

[/Script/Engine.UserInterfaceSettings]

; TODO: Change RenderFocusRule to Never before shipping.

RenderFocusRule                     = Always
UIScaleRule                         = Custom
CustomScalingRuleClass              = /Script/Re.ReDPIScalingRule

[/Script/Engine.Engine]

AssetManagerClassName               = /Script/Re.ReAssetManager

bSmoothFrameRate                    = false
bPauseOnLossOfFocus                 = false
bAllowMatureLanguage                = true

[/Script/UnrealEd.EditorEngine]

bSmoothFrameRate                    = false

[/Script/EngineSettings.GameMapsSettings]

GameInstanceClass                   = /Script/Re.ReGameInstance
EditorStartupMap                    = /Game/Root/Levels/LV_Persistent.LV_Persistent
GameDefaultMap                      = /Game/Root/Levels/LV_Persistent.LV_Persistent
GlobalDefaultGameMode               = /Script/Re.ReGameMode

[/Script/Engine.CollisionProfile]

+DefaultChannelResponses            = (Channel = ECC_GameTraceChannel1, DefaultResponse = ECR_Ignore, bTraceType = True, bStaticObject = False, Name = "MovementPlane"  )
+DefaultChannelResponses            = (Channel = ECC_GameTraceChannel2, DefaultResponse = ECR_Ignore, bTraceType = True, bStaticObject = False, Name = "Interactable"   )

[/Script/Engine.RendererSettings]

; Lumen

r.DynamicGlobalIlluminationMethod                                               = 1
r.ReflectionMethod                                                              = 1

; Hardware RT

r.RayTracing                                                                    = True
r.Lumen.HardwareRayTracing                                                      = True
r.Lumen.HardwareRayTracing.LightingMode                                         = 0
r.RayTracing.Shadows                                                            = True
r.PathTracing                                                                   = False
r.SkinCache.CompileShaders                                                      = 1
r.RayTracing.RayTracingProxies.ProjectEnabled                                   = True
r.Lumen.TranslucencyReflections.FrontLayer.EnableForProject                     = True
r.Lumen.Reflections.HardwareRayTracing.Translucent.Refraction.EnableForProject  = False

; Post Processing

r.AntiAliasingMethod                                                            = 0
r.DefaultFeature.AmbientOcclusion                                               = False
r.DefaultFeature.AutoExposure                                                   = False
r.DefaultFeature.Bloom                                                          = False
r.DefaultFeature.MotionBlur                                                     = False
r.DefaultFeature.LensFlare                                                      = False

; Other

r.AllowStaticLighting                                                           = False
r.Shadow.Virtual.Enable                                                         = 1
r.VirtualTextures                                                               = 1
r.GenerateMeshDistanceFields                                                    = True
r.Substrate                                                                     = True

[/Script/WindowsTargetPlatform.WindowsTargetSettings]

DefaultGraphicsRHI                  = DefaultGraphicsRHI_DX12
+D3D12TargetedShaderFormats         = PCD3D_SM6
-D3D12TargetedShaderFormats         = PCD3D_SM5
RayTracingMode                      = Inline
bGenerateNaniteFallbackMeshes       = False

[/Script/HardwareTargeting.HardwareTargetingSettings]

TargetedHardwareClass               = Desktop
AppliedTargetedHardwareClass        = Desktop
DefaultGraphicsPerformance          = Scalable
AppliedDefaultGraphicsPerformance   = Scalable
