[/Script/EngineSettings.GeneralProjectSettings]

ProjectID                               = DF482489423153B6D9FE7CAAA9F3DAD4
ProjectName                             = Re
CopyrightNotice                         = Copyright (c) 2026 Mahian Ishraq. All rights reserved.

[/Script/Engine.AssetManagerSettings]

bShouldManagerDetermineTypeAndName      = True

[/Script/UnrealEd.ProjectPackagingSettings]

FullRebuild                             = False
IncludePrerequisites                    = False
UsePakFile                              = True
bUseIoStore                             = True
bMakeBinaryConfig                       = True
bShareMaterialShaderCode                = False
bCompressed                             = False

## Package Custom Hardware Cursors ##

+DirectoriesToAlwaysStageAsUFS          = (Path = "Root/Assets/Texture/UI/Pointer")
